### ISSUE TITLE
DAIC-WOZ Databas downloading

### ISSUE THREAD

**Issue by fedicherif** [kykiefer/depression-detect#1]
Thank you for this great work.
So, how should I proceed for downloading DAIC-WOZ Database?

**Comment by kykiefer** [comment]
Please see the website for instructions: http://dcapswoz.ict.usc.edu/

**Comment by N2641785298** [comment]
https://dcapswoz.ict.usc.edu/daic-woz-database-download/
After filling out the application information on this website, what happens when I click submit and there is no response?

**Comment by faaiz99** [comment]
Same Problem

> https://dcapswoz.ict.usc.edu/daic-woz-database-download/ After filling out the application information on this website, what happens when I click submit and there is no response?

**Comment by MysticShadow427** [comment]
how to preprocess this data? what are the steps to analyse the txt and csv files to come up with videos?

**Comment by Akashh72** [comment]
anyone have DAIC-WoZ data please provide me the official website it not opening and not able to download this dataset.
