### ISSUE TITLE
There are errors in Random Sampling:

### ISSUE THREAD

**Issue by wuqing778** [kykiefer/depression-detect#10]
Hello, I'm sorry to bother you.I am trying to reproduce the experimental results of your work.But there is error in random_sampling: traceability
(Last call was last) :
文件“ E：/学习/ progress-pycharm / CNN +频谱
create_sample_dicts（crop_width = 125）
文件“ E：/学习/ progress-pycharm / CNN +频谱图抑郁识别-奇基弗/特征/ random_sampling ”中的图抑郁识别-奇基弗/特征/random_sampling.py”，第240行。 py”，在create_sample_dictscrop_width
= crop_width中的第127行）
文件“ E：/学习/ progress-pycharm / CNN +频谱图抑郁识别-奇基弗/特征/random_sampling.py”，在52行中，在
define_num_crops shortest_clip = min（merged_dict .items（），key = lambda x：x [1] .shape [1]）
ValueError：min（）arg是一个空序列
How can I solve it? Python3.5 for the environment

**Comment by himanshuchuri** [comment]
Have you solved the error. Apparently I am also getting the same error message

**Comment by wuqing778** [comment]
Hello, I have solved this problem, but the training effect is not good, the accuracy can only reach 50%, the confusion matrix seems wrong, may I ask how to solve this problem, thank you
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kykiefer/depression-detect"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月11日(星期五) 下午4:11
收件人:&nbsp;"kykiefer/depression-detect"<depression-detect@noreply.github.com&gt;;
抄送:&nbsp;"1359415123"<1359415123@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [kykiefer/depression-detect] There are errors in Random Sampling: (#10)





 
Have you solved the error. Apparently I am also getting the same error message

**Comment by Githubhgh** [comment]
Yes,I try it on my own dataset,the results are always 50%

**Comment by UmaYadav** [comment]
Can you Please provide the correct solution of random sampling code. As I am also getting error in random.sample().
