### ISSUE TITLE
Backend as tensorflow instead of  theano

### ISSUE THREAD

**Issue by genandlam** [kykiefer/depression-detect#2]
Hi kykiefer, 

Thank you for your great work, Can I ask if I were to change the backend as tensorflow instead of theano. How should I go about to produce the same result as yours.

**Comment by kykiefer** [comment]
I haven't visited this code in awhile, but seems like there's some good resources out there for converting backends. https://github.com/keras-team/keras/wiki/Converting-convolution-kernels-from-Theano-to-TensorFlow-and-vice-versa

**Comment by genandlam** [comment]
Thank you so much!
