### ISSUE TITLE
 FileNotFoundError: [Errno 2] No such file or directory: 'Paudio\\300_75.18-76.72.wav'

### ISSUE THREAD

**Issue by Afef00** [kykiefer/depression-detect#5]
I tried to run the segmentation part ( segmentation.py ) but  i got this error message 

> File "C:/Users/Afef-/Desktop/depression detection/depression-detect-master/src/data/segmentation.py", line 60, in remove_silence
>     wavfile.write(seg_name, Fs, x[int(Fs * s[0]):int(Fs * s[1])]) 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\io\wavfile.py", line 328, in write
>     fid = open(filename, 'wb')
> FileNotFoundError: [Errno 2] No such file or directory: 'Paudio\\300_75.18-76.72.wav'
I verified the dir_name , i don't get where the problem is ?

**Comment by djsurani** [comment]
had  you got solution ?

**Comment by djsurani** [comment]
I am having same error
