### ISSUE TITLE
Cannot find "cnn_aws.py"

### ISSUE THREAD

**Issue by Kelvinmao** [kykiefer/depression-detect#6]
Hi Kiefer

I 'm trying to obtain the trained model file. In the README.md, you mentioned that it can be accessed by running "cnn_aws.py". But I cannot find this file in the project. Is it removed?

**Comment by tanshanghehe** [comment]
Hi,Have you solved the problem yet?I can't find this file either😂.

**Comment by Kelvinmao** [comment]
> Hi,Have you solved the problem yet?I can't find this file either😂.

Sorry I didn't. I start to train my own model.

**Comment by tanshanghehe** [comment]
em,thanks.😂

**Comment by kykiefer** [comment]
`cnn.py` will train the model. `cnn_aws.py` was a script that utilized my AWS accounts GPUs. `cnn.py` can be adapted to utilize GPUs if desired.
