### ISSUE TITLE
CNN on my Machine

### ISSUE THREAD

**Issue by Bhavya100** [kykiefer/depression-detect#7]
You have used CNN on AWS. But, I want to implement CNN on my machine. How much time would it take? I have an intel i5 8th generation and 4GB Nvidia 940MX. Also which libraries should I use?

**Comment by kykiefer** [comment]
I don't know how long it will take to train on your local machine. I'd recommend using something like this package (https://github.com/bndr/pipreqs) to figure out the library requirements and then install them in a Docker container as a playground for this repo.
